// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DewaSRY/core-service/internal/db/store (interfaces: Storer)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination internal/db/mock/querier.go github.com/DewaSRY/core-service/internal/db/store Storer
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/DewaSRY/core-service/internal/db/sqlc"
	store "github.com/DewaSRY/core-service/internal/db/store"
	gomock "go.uber.org/mock/gomock"
)

// MockStorer is a mock of Storer interface.
type MockStorer struct {
	ctrl     *gomock.Controller
	recorder *MockStorerMockRecorder
	isgomock struct{}
}

// MockStorerMockRecorder is the mock recorder for MockStorer.
type MockStorerMockRecorder struct {
	mock *MockStorer
}

// NewMockStorer creates a new mock instance.
func NewMockStorer(ctrl *gomock.Controller) *MockStorer {
	mock := &MockStorer{ctrl: ctrl}
	mock.recorder = &MockStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorer) EXPECT() *MockStorerMockRecorder {
	return m.recorder
}

// AccountEntriesByAccountId mocks base method.
func (m *MockStorer) AccountEntriesByAccountId(ctx context.Context, id int64) (db.AccountEntriesByAccountIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountEntriesByAccountId", ctx, id)
	ret0, _ := ret[0].(db.AccountEntriesByAccountIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountEntriesByAccountId indicates an expected call of AccountEntriesByAccountId.
func (mr *MockStorerMockRecorder) AccountEntriesByAccountId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountEntriesByAccountId", reflect.TypeOf((*MockStorer)(nil).AccountEntriesByAccountId), ctx, id)
}

// BindUserDeviceFingerprint mocks base method.
func (m *MockStorer) BindUserDeviceFingerprint(ctx context.Context, arg db.BindUserDeviceFingerprintParams) (db.BindUserDeviceFingerprintRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindUserDeviceFingerprint", ctx, arg)
	ret0, _ := ret[0].(db.BindUserDeviceFingerprintRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BindUserDeviceFingerprint indicates an expected call of BindUserDeviceFingerprint.
func (mr *MockStorerMockRecorder) BindUserDeviceFingerprint(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindUserDeviceFingerprint", reflect.TypeOf((*MockStorer)(nil).BindUserDeviceFingerprint), ctx, arg)
}

// CheckIsAccountWithIdExist mocks base method.
func (m *MockStorer) CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsAccountWithIdExist", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsAccountWithIdExist indicates an expected call of CheckIsAccountWithIdExist.
func (mr *MockStorerMockRecorder) CheckIsAccountWithIdExist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsAccountWithIdExist", reflect.TypeOf((*MockStorer)(nil).CheckIsAccountWithIdExist), ctx, id)
}

// CheckIsUsernameExist mocks base method.
func (m *MockStorer) CheckIsUsernameExist(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsUsernameExist", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsUsernameExist indicates an expected call of CheckIsUsernameExist.
func (mr *MockStorerMockRecorder) CheckIsUsernameExist(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsUsernameExist", reflect.TypeOf((*MockStorer)(nil).CheckIsUsernameExist), ctx, username)
}

// CountAccountEntriesByAccountId mocks base method.
func (m *MockStorer) CountAccountEntriesByAccountId(ctx context.Context, arg db.CountAccountEntriesByAccountIdParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountEntriesByAccountId", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountEntriesByAccountId indicates an expected call of CountAccountEntriesByAccountId.
func (mr *MockStorerMockRecorder) CountAccountEntriesByAccountId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountEntriesByAccountId", reflect.TypeOf((*MockStorer)(nil).CountAccountEntriesByAccountId), ctx, arg)
}

// CountAccountTransactionHistory mocks base method.
func (m *MockStorer) CountAccountTransactionHistory(ctx context.Context, arg db.CountAccountTransactionHistoryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountTransactionHistory", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountTransactionHistory indicates an expected call of CountAccountTransactionHistory.
func (mr *MockStorerMockRecorder) CountAccountTransactionHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountTransactionHistory", reflect.TypeOf((*MockStorer)(nil).CountAccountTransactionHistory), ctx, arg)
}

// CountAccountsByUserId mocks base method.
func (m *MockStorer) CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountsByUserId", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountsByUserId indicates an expected call of CountAccountsByUserId.
func (mr *MockStorerMockRecorder) CountAccountsByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountsByUserId", reflect.TypeOf((*MockStorer)(nil).CountAccountsByUserId), ctx, userID)
}

// CountAccountsSearchByUserNumber mocks base method.
func (m *MockStorer) CountAccountsSearchByUserNumber(ctx context.Context, number sql.NullString) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountsSearchByUserNumber", ctx, number)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountsSearchByUserNumber indicates an expected call of CountAccountsSearchByUserNumber.
func (mr *MockStorerMockRecorder) CountAccountsSearchByUserNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountsSearchByUserNumber", reflect.TypeOf((*MockStorer)(nil).CountAccountsSearchByUserNumber), ctx, number)
}

// CreateAccount mocks base method.
func (m *MockStorer) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStorerMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStorer)(nil).CreateAccount), ctx, arg)
}

// CreateAccountTx mocks base method.
func (m *MockStorer) CreateAccountTx(ctx context.Context, arg store.CreateAccountTxParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountTx", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountTx indicates an expected call of CreateAccountTx.
func (mr *MockStorerMockRecorder) CreateAccountTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountTx", reflect.TypeOf((*MockStorer)(nil).CreateAccountTx), ctx, arg)
}

// CreateEntries mocks base method.
func (m *MockStorer) CreateEntries(ctx context.Context, arg db.CreateEntriesParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntries", ctx, arg)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntries indicates an expected call of CreateEntries.
func (mr *MockStorerMockRecorder) CreateEntries(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntries", reflect.TypeOf((*MockStorer)(nil).CreateEntries), ctx, arg)
}

// CreateTransfer mocks base method.
func (m *MockStorer) CreateTransfer(ctx context.Context, arg db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, arg)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockStorerMockRecorder) CreateTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockStorer)(nil).CreateTransfer), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStorer) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorerMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorer)(nil).CreateUser), ctx, arg)
}

// DeleteAccountTx mocks base method.
func (m *MockStorer) DeleteAccountTx(ctx context.Context, arg store.DeleteAccountTxParams) (store.DeleteAccountTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountTx", ctx, arg)
	ret0, _ := ret[0].(store.DeleteAccountTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccountTx indicates an expected call of DeleteAccountTx.
func (mr *MockStorerMockRecorder) DeleteAccountTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountTx", reflect.TypeOf((*MockStorer)(nil).DeleteAccountTx), ctx, arg)
}

// DepositTx mocks base method.
func (m *MockStorer) DepositTx(ctx context.Context, arg store.DepositTxParams) (store.DepositTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DepositTx", ctx, arg)
	ret0, _ := ret[0].(store.DepositTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DepositTx indicates an expected call of DepositTx.
func (mr *MockStorerMockRecorder) DepositTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DepositTx", reflect.TypeOf((*MockStorer)(nil).DepositTx), ctx, arg)
}

// GetAccountById mocks base method.
func (m *MockStorer) GetAccountById(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountById", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountById indicates an expected call of GetAccountById.
func (mr *MockStorerMockRecorder) GetAccountById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountById", reflect.TypeOf((*MockStorer)(nil).GetAccountById), ctx, id)
}

// GetAccountByIdForUpdate mocks base method.
func (m *MockStorer) GetAccountByIdForUpdate(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByIdForUpdate", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByIdForUpdate indicates an expected call of GetAccountByIdForUpdate.
func (mr *MockStorerMockRecorder) GetAccountByIdForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByIdForUpdate", reflect.TypeOf((*MockStorer)(nil).GetAccountByIdForUpdate), ctx, id)
}

// GetAccountViewById mocks base method.
func (m *MockStorer) GetAccountViewById(ctx context.Context, id int64) (db.GetAccountViewByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountViewById", ctx, id)
	ret0, _ := ret[0].(db.GetAccountViewByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountViewById indicates an expected call of GetAccountViewById.
func (mr *MockStorerMockRecorder) GetAccountViewById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountViewById", reflect.TypeOf((*MockStorer)(nil).GetAccountViewById), ctx, id)
}

// GetMainAccountByUserId mocks base method.
func (m *MockStorer) GetMainAccountByUserId(ctx context.Context, userID sql.NullInt64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainAccountByUserId", ctx, userID)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMainAccountByUserId indicates an expected call of GetMainAccountByUserId.
func (mr *MockStorerMockRecorder) GetMainAccountByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainAccountByUserId", reflect.TypeOf((*MockStorer)(nil).GetMainAccountByUserId), ctx, userID)
}

// GetTransferById mocks base method.
func (m *MockStorer) GetTransferById(ctx context.Context, id int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferById", ctx, id)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransferById indicates an expected call of GetTransferById.
func (mr *MockStorerMockRecorder) GetTransferById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferById", reflect.TypeOf((*MockStorer)(nil).GetTransferById), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockStorer) GetUserByEmail(ctx context.Context, email string) (db.GetUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.GetUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStorerMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStorer)(nil).GetUserByEmail), ctx, email)
}

// GetUserById mocks base method.
func (m *MockStorer) GetUserById(ctx context.Context, id int64) (db.GetUserByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(db.GetUserByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockStorerMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockStorer)(nil).GetUserById), ctx, id)
}

// IncrementAccountBalance mocks base method.
func (m *MockStorer) IncrementAccountBalance(ctx context.Context, arg db.IncrementAccountBalanceParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAccountBalance", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAccountBalance indicates an expected call of IncrementAccountBalance.
func (mr *MockStorerMockRecorder) IncrementAccountBalance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAccountBalance", reflect.TypeOf((*MockStorer)(nil).IncrementAccountBalance), ctx, arg)
}

// ListAccountEntriesByAccountId mocks base method.
func (m *MockStorer) ListAccountEntriesByAccountId(ctx context.Context, arg db.ListAccountEntriesByAccountIdParams) ([]db.ListAccountEntriesByAccountIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountEntriesByAccountId", ctx, arg)
	ret0, _ := ret[0].([]db.ListAccountEntriesByAccountIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountEntriesByAccountId indicates an expected call of ListAccountEntriesByAccountId.
func (mr *MockStorerMockRecorder) ListAccountEntriesByAccountId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountEntriesByAccountId", reflect.TypeOf((*MockStorer)(nil).ListAccountEntriesByAccountId), ctx, arg)
}

// ListAccountTransactionHistory mocks base method.
func (m *MockStorer) ListAccountTransactionHistory(ctx context.Context, arg db.ListAccountTransactionHistoryParams) ([]db.ListAccountTransactionHistoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountTransactionHistory", ctx, arg)
	ret0, _ := ret[0].([]db.ListAccountTransactionHistoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountTransactionHistory indicates an expected call of ListAccountTransactionHistory.
func (mr *MockStorerMockRecorder) ListAccountTransactionHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountTransactionHistory", reflect.TypeOf((*MockStorer)(nil).ListAccountTransactionHistory), ctx, arg)
}

// ListAccountsSearchByUserNumber mocks base method.
func (m *MockStorer) ListAccountsSearchByUserNumber(ctx context.Context, arg db.ListAccountsSearchByUserNumberParams) ([]db.ListAccountsSearchByUserNumberRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsSearchByUserNumber", ctx, arg)
	ret0, _ := ret[0].([]db.ListAccountsSearchByUserNumberRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountsSearchByUserNumber indicates an expected call of ListAccountsSearchByUserNumber.
func (mr *MockStorerMockRecorder) ListAccountsSearchByUserNumber(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsSearchByUserNumber", reflect.TypeOf((*MockStorer)(nil).ListAccountsSearchByUserNumber), ctx, arg)
}

// ListMeAccountsByUserId mocks base method.
func (m *MockStorer) ListMeAccountsByUserId(ctx context.Context, arg db.ListMeAccountsByUserIdParams) ([]db.ListMeAccountsByUserIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeAccountsByUserId", ctx, arg)
	ret0, _ := ret[0].([]db.ListMeAccountsByUserIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeAccountsByUserId indicates an expected call of ListMeAccountsByUserId.
func (mr *MockStorerMockRecorder) ListMeAccountsByUserId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeAccountsByUserId", reflect.TypeOf((*MockStorer)(nil).ListMeAccountsByUserId), ctx, arg)
}

// ListMeAccountsByUserIdCount mocks base method.
func (m *MockStorer) ListMeAccountsByUserIdCount(ctx context.Context, arg db.ListMeAccountsByUserIdCountParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeAccountsByUserIdCount", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeAccountsByUserIdCount indicates an expected call of ListMeAccountsByUserIdCount.
func (mr *MockStorerMockRecorder) ListMeAccountsByUserIdCount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeAccountsByUserIdCount", reflect.TypeOf((*MockStorer)(nil).ListMeAccountsByUserIdCount), ctx, arg)
}

// ListRecentTransferDestinations mocks base method.
func (m *MockStorer) ListRecentTransferDestinations(ctx context.Context, arg db.ListRecentTransferDestinationsParams) ([]db.ListRecentTransferDestinationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentTransferDestinations", ctx, arg)
	ret0, _ := ret[0].([]db.ListRecentTransferDestinationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentTransferDestinations indicates an expected call of ListRecentTransferDestinations.
func (mr *MockStorerMockRecorder) ListRecentTransferDestinations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentTransferDestinations", reflect.TypeOf((*MockStorer)(nil).ListRecentTransferDestinations), ctx, arg)
}

// SoftDeleteAccount mocks base method.
func (m *MockStorer) SoftDeleteAccount(ctx context.Context, id int64) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAccount", ctx, id)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteAccount indicates an expected call of SoftDeleteAccount.
func (mr *MockStorerMockRecorder) SoftDeleteAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAccount", reflect.TypeOf((*MockStorer)(nil).SoftDeleteAccount), ctx, id)
}

// TransferTx mocks base method.
func (m *MockStorer) TransferTx(ctx context.Context, arg db.CreateTransferParams) (store.TransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTx", ctx, arg)
	ret0, _ := ret[0].(store.TransferTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferTx indicates an expected call of TransferTx.
func (mr *MockStorerMockRecorder) TransferTx(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTx", reflect.TypeOf((*MockStorer)(nil).TransferTx), ctx, arg)
}

// UpdateAccount mocks base method.
func (m *MockStorer) UpdateAccount(ctx context.Context, arg db.UpdateAccountParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockStorerMockRecorder) UpdateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockStorer)(nil).UpdateAccount), ctx, arg)
}

// UpdateAccountNumber mocks base method.
func (m *MockStorer) UpdateAccountNumber(ctx context.Context, arg db.UpdateAccountNumberParams) (db.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountNumber", ctx, arg)
	ret0, _ := ret[0].(db.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountNumber indicates an expected call of UpdateAccountNumber.
func (mr *MockStorerMockRecorder) UpdateAccountNumber(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountNumber", reflect.TypeOf((*MockStorer)(nil).UpdateAccountNumber), ctx, arg)
}
