services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-simple_bank}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-simple_bank}
    ports:
      - "5433:5432"
    volumes:
      - simple_bank_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-simple_bank} -d ${POSTGRES_DB:-simple_bank}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  # core-services:
  #   image: ${CORE_SERVICE_IMAGE}
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  # nginx:
  #   image: nginx:1.27-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./apps/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - core-services

volumes:
  simple_bank_postgres_data:
