// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DewaSRY/core-service/db/sqlc (interfaces: Querier)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/querier.go github.com/DewaSRY/core-service/db/sqlc Querier
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/DewaSRY/core-service/db/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CheckIsAccountWithIdExist mocks base method.
func (m *MockQuerier) CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsAccountWithIdExist", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsAccountWithIdExist indicates an expected call of CheckIsAccountWithIdExist.
func (mr *MockQuerierMockRecorder) CheckIsAccountWithIdExist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsAccountWithIdExist", reflect.TypeOf((*MockQuerier)(nil).CheckIsAccountWithIdExist), ctx, id)
}

// CheckIsUsernameExist mocks base method.
func (m *MockQuerier) CheckIsUsernameExist(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsUsernameExist", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsUsernameExist indicates an expected call of CheckIsUsernameExist.
func (mr *MockQuerierMockRecorder) CheckIsUsernameExist(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsUsernameExist", reflect.TypeOf((*MockQuerier)(nil).CheckIsUsernameExist), ctx, username)
}

// CountAccountTransactionHistory mocks base method.
func (m *MockQuerier) CountAccountTransactionHistory(ctx context.Context, arg db.CountAccountTransactionHistoryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountTransactionHistory", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountTransactionHistory indicates an expected call of CountAccountTransactionHistory.
func (mr *MockQuerierMockRecorder) CountAccountTransactionHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountTransactionHistory", reflect.TypeOf((*MockQuerier)(nil).CountAccountTransactionHistory), ctx, arg)
}

// CountAccountsByUserId mocks base method.
func (m *MockQuerier) CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAccountsByUserId", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAccountsByUserId indicates an expected call of CountAccountsByUserId.
func (mr *MockQuerierMockRecorder) CountAccountsByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAccountsByUserId", reflect.TypeOf((*MockQuerier)(nil).CountAccountsByUserId), ctx, userID)
}

// CountEntriesByAccount mocks base method.
func (m *MockQuerier) CountEntriesByAccount(ctx context.Context, accountID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEntriesByAccount", ctx, accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEntriesByAccount indicates an expected call of CountEntriesByAccount.
func (mr *MockQuerierMockRecorder) CountEntriesByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEntriesByAccount", reflect.TypeOf((*MockQuerier)(nil).CountEntriesByAccount), ctx, accountID)
}

// CreateAccount mocks base method.
func (m *MockQuerier) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.CreateAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(db.CreateAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockQuerierMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockQuerier)(nil).CreateAccount), ctx, arg)
}

// CreateEntries mocks base method.
func (m *MockQuerier) CreateEntries(ctx context.Context, arg db.CreateEntriesParams) (db.CreateEntriesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntries", ctx, arg)
	ret0, _ := ret[0].(db.CreateEntriesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntries indicates an expected call of CreateEntries.
func (mr *MockQuerierMockRecorder) CreateEntries(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntries", reflect.TypeOf((*MockQuerier)(nil).CreateEntries), ctx, arg)
}

// CreateTransfer mocks base method.
func (m *MockQuerier) CreateTransfer(ctx context.Context, arg db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, arg)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockQuerierMockRecorder) CreateTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockQuerier)(nil).CreateTransfer), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// FindAccountByNumber mocks base method.
func (m *MockQuerier) FindAccountByNumber(ctx context.Context, number sql.NullString) (db.FindAccountByNumberRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountByNumber", ctx, number)
	ret0, _ := ret[0].(db.FindAccountByNumberRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountByNumber indicates an expected call of FindAccountByNumber.
func (mr *MockQuerierMockRecorder) FindAccountByNumber(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountByNumber", reflect.TypeOf((*MockQuerier)(nil).FindAccountByNumber), ctx, number)
}

// GetAccountById mocks base method.
func (m *MockQuerier) GetAccountById(ctx context.Context, id int64) (db.GetAccountByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountById", ctx, id)
	ret0, _ := ret[0].(db.GetAccountByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountById indicates an expected call of GetAccountById.
func (mr *MockQuerierMockRecorder) GetAccountById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountById", reflect.TypeOf((*MockQuerier)(nil).GetAccountById), ctx, id)
}

// GetAccountByIdForUpdate mocks base method.
func (m *MockQuerier) GetAccountByIdForUpdate(ctx context.Context, id int64) (db.GetAccountByIdForUpdateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByIdForUpdate", ctx, id)
	ret0, _ := ret[0].(db.GetAccountByIdForUpdateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByIdForUpdate indicates an expected call of GetAccountByIdForUpdate.
func (mr *MockQuerierMockRecorder) GetAccountByIdForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByIdForUpdate", reflect.TypeOf((*MockQuerier)(nil).GetAccountByIdForUpdate), ctx, id)
}

// GetMainAccountByUserId mocks base method.
func (m *MockQuerier) GetMainAccountByUserId(ctx context.Context, userID sql.NullInt64) (db.GetMainAccountByUserIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainAccountByUserId", ctx, userID)
	ret0, _ := ret[0].(db.GetMainAccountByUserIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMainAccountByUserId indicates an expected call of GetMainAccountByUserId.
func (mr *MockQuerierMockRecorder) GetMainAccountByUserId(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainAccountByUserId", reflect.TypeOf((*MockQuerier)(nil).GetMainAccountByUserId), ctx, userID)
}

// GetTransferById mocks base method.
func (m *MockQuerier) GetTransferById(ctx context.Context, id int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferById", ctx, id)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransferById indicates an expected call of GetTransferById.
func (mr *MockQuerierMockRecorder) GetTransferById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferById", reflect.TypeOf((*MockQuerier)(nil).GetTransferById), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (db.GetUserByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.GetUserByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserById mocks base method.
func (m *MockQuerier) GetUserById(ctx context.Context, id int64) (db.GetUserByIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, id)
	ret0, _ := ret[0].(db.GetUserByIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockQuerierMockRecorder) GetUserById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockQuerier)(nil).GetUserById), ctx, id)
}

// IncrementAccountBalance mocks base method.
func (m *MockQuerier) IncrementAccountBalance(ctx context.Context, arg db.IncrementAccountBalanceParams) (db.IncrementAccountBalanceRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAccountBalance", ctx, arg)
	ret0, _ := ret[0].(db.IncrementAccountBalanceRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementAccountBalance indicates an expected call of IncrementAccountBalance.
func (mr *MockQuerierMockRecorder) IncrementAccountBalance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAccountBalance", reflect.TypeOf((*MockQuerier)(nil).IncrementAccountBalance), ctx, arg)
}

// ListAccountTransactionHistory mocks base method.
func (m *MockQuerier) ListAccountTransactionHistory(ctx context.Context, arg db.ListAccountTransactionHistoryParams) ([]db.ListAccountTransactionHistoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountTransactionHistory", ctx, arg)
	ret0, _ := ret[0].([]db.ListAccountTransactionHistoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountTransactionHistory indicates an expected call of ListAccountTransactionHistory.
func (mr *MockQuerierMockRecorder) ListAccountTransactionHistory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountTransactionHistory", reflect.TypeOf((*MockQuerier)(nil).ListAccountTransactionHistory), ctx, arg)
}

// ListAccountsByUserId mocks base method.
func (m *MockQuerier) ListAccountsByUserId(ctx context.Context, arg db.ListAccountsByUserIdParams) ([]db.ListAccountsByUserIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsByUserId", ctx, arg)
	ret0, _ := ret[0].([]db.ListAccountsByUserIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountsByUserId indicates an expected call of ListAccountsByUserId.
func (mr *MockQuerierMockRecorder) ListAccountsByUserId(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsByUserId", reflect.TypeOf((*MockQuerier)(nil).ListAccountsByUserId), ctx, arg)
}

// ListEntriesByAccount mocks base method.
func (m *MockQuerier) ListEntriesByAccount(ctx context.Context, arg db.ListEntriesByAccountParams) ([]db.ListEntriesByAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntriesByAccount", ctx, arg)
	ret0, _ := ret[0].([]db.ListEntriesByAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntriesByAccount indicates an expected call of ListEntriesByAccount.
func (mr *MockQuerierMockRecorder) ListEntriesByAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntriesByAccount", reflect.TypeOf((*MockQuerier)(nil).ListEntriesByAccount), ctx, arg)
}

// ListRecentTransferDestinations mocks base method.
func (m *MockQuerier) ListRecentTransferDestinations(ctx context.Context, arg db.ListRecentTransferDestinationsParams) ([]db.ListRecentTransferDestinationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentTransferDestinations", ctx, arg)
	ret0, _ := ret[0].([]db.ListRecentTransferDestinationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentTransferDestinations indicates an expected call of ListRecentTransferDestinations.
func (mr *MockQuerierMockRecorder) ListRecentTransferDestinations(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentTransferDestinations", reflect.TypeOf((*MockQuerier)(nil).ListRecentTransferDestinations), ctx, arg)
}

// SoftDeleteAccount mocks base method.
func (m *MockQuerier) SoftDeleteAccount(ctx context.Context, id int64) (db.SoftDeleteAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAccount", ctx, id)
	ret0, _ := ret[0].(db.SoftDeleteAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteAccount indicates an expected call of SoftDeleteAccount.
func (mr *MockQuerierMockRecorder) SoftDeleteAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAccount", reflect.TypeOf((*MockQuerier)(nil).SoftDeleteAccount), ctx, id)
}

// UpdateAccount mocks base method.
func (m *MockQuerier) UpdateAccount(ctx context.Context, arg db.UpdateAccountParams) (db.UpdateAccountRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, arg)
	ret0, _ := ret[0].(db.UpdateAccountRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockQuerierMockRecorder) UpdateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockQuerier)(nil).UpdateAccount), ctx, arg)
}

// UpdateAccountNumber mocks base method.
func (m *MockQuerier) UpdateAccountNumber(ctx context.Context, arg db.UpdateAccountNumberParams) (db.UpdateAccountNumberRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountNumber", ctx, arg)
	ret0, _ := ret[0].(db.UpdateAccountNumberRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountNumber indicates an expected call of UpdateAccountNumber.
func (mr *MockQuerierMockRecorder) UpdateAccountNumber(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountNumber", reflect.TypeOf((*MockQuerier)(nil).UpdateAccountNumber), ctx, arg)
}
