// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account-transaction.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkIsAccountWithIdExist = `-- name: CheckIsAccountWithIdExist :one
SELECT EXISTS (
    SELECT 1
    FROM accounts
    WHERE id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error) {
	row := q.queryRow(ctx, q.checkIsAccountWithIdExistStmt, checkIsAccountWithIdExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAccountByIdForUpdate = `-- name: GetAccountByIdForUpdate :one
SELECT id, balance, currency, user_id, number, name, description, is_main, created_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type GetAccountByIdForUpdateRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetAccountByIdForUpdate(ctx context.Context, id int64) (GetAccountByIdForUpdateRow, error) {
	row := q.queryRow(ctx, q.getAccountByIdForUpdateStmt, getAccountByIdForUpdate, id)
	var i GetAccountByIdForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountViewById = `-- name: GetAccountViewById :one
SELECT 
    id,
    balance,
    currency,
    created_at,
    updated_at,
    user_id,
    name,
    description,
    is_main,
    username,
    number
FROM account_user_details_view
WHERE id = $1
`

type GetAccountViewByIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserID      sql.NullInt64  `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	Username    sql.NullString `json:"username"`
	Number      sql.NullString `json:"number"`
}

func (q *Queries) GetAccountViewById(ctx context.Context, id int64) (GetAccountViewByIdRow, error) {
	row := q.queryRow(ctx, q.getAccountViewByIdStmt, getAccountViewById, id)
	var i GetAccountViewByIdRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.Username,
		&i.Number,
	)
	return i, err
}

const incrementAccountBalance = `-- name: IncrementAccountBalance :one
UPDATE accounts
SET balance =  balance + $2, updated_at = now()
WHERE id = $1
RETURNING id, balance, currency, user_id, number, name, description, is_main, created_at
`

type IncrementAccountBalanceParams struct {
	ID      int64  `json:"id"`
	Balance string `json:"balance"`
}

type IncrementAccountBalanceRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (IncrementAccountBalanceRow, error) {
	row := q.queryRow(ctx, q.incrementAccountBalanceStmt, incrementAccountBalance, arg.ID, arg.Balance)
	var i IncrementAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentTransferDestinations = `-- name: ListRecentTransferDestinations :many
SELECT id, name, number, last_used_at FROM (
    SELECT DISTINCT ON (a.id) a.id, a.name, a.number, t.created_at AS last_used_at
    FROM transfers t
    JOIN accounts a ON a.id = t.to_account_id
    WHERE t.from_account_id = $1 AND a.deleted_at IS NULL
    ORDER BY a.id, t.created_at DESC
) recent_destinations
ORDER BY last_used_at DESC
LIMIT $2
`

type ListRecentTransferDestinationsParams struct {
	FromAccountID int64 `json:"from_account_id"`
	LimitCount    int32 `json:"limit_count"`
}

type ListRecentTransferDestinationsRow struct {
	ID         int64          `json:"id"`
	Name       sql.NullString `json:"name"`
	Number     sql.NullString `json:"number"`
	LastUsedAt time.Time      `json:"last_used_at"`
}

func (q *Queries) ListRecentTransferDestinations(ctx context.Context, arg ListRecentTransferDestinationsParams) ([]ListRecentTransferDestinationsRow, error) {
	rows, err := q.query(ctx, q.listRecentTransferDestinationsStmt, listRecentTransferDestinations, arg.FromAccountID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentTransferDestinationsRow{}
	for rows.Next() {
		var i ListRecentTransferDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Number,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
