// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkIsAccountWithIdExist = `-- name: CheckIsAccountWithIdExist :one
SELECT EXISTS (
    SELECT 1
    FROM accounts
    WHERE id = $1
)
`

func (q *Queries) CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error) {
	row := q.queryRow(ctx, q.checkIsAccountWithIdExistStmt, checkIsAccountWithIdExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAccountsByUserId = `-- name: CountAccountsByUserId :one
SELECT COUNT(*) FROM accounts
WHERE user_id = $1
`

func (q *Queries) CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsByUserIdStmt, countAccountsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    number, 
    name,
    description,
    balance,
    currency, 
    user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, balance, currency, user_id, number, name, description, created_at
`

type CreateAccountParams struct {
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
}

type CreateAccountRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.Balance,
		arg.Currency,
		arg.UserID,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, balance, currency, user_id, number, name, description, created_at
FROM accounts
WHERE id = $1
`

type GetAccountByIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetAccountById(ctx context.Context, id int64) (GetAccountByIdRow, error) {
	row := q.queryRow(ctx, q.getAccountByIdStmt, getAccountById, id)
	var i GetAccountByIdRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByIdForUpdate = `-- name: GetAccountByIdForUpdate :one
SELECT id, balance, currency, user_id, number, name, description, created_at
FROM accounts
WHERE id = $1
FOR UPDATE
`

type GetAccountByIdForUpdateRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetAccountByIdForUpdate(ctx context.Context, id int64) (GetAccountByIdForUpdateRow, error) {
	row := q.queryRow(ctx, q.getAccountByIdForUpdateStmt, getAccountByIdForUpdate, id)
	var i GetAccountByIdForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAccountBalance = `-- name: IncrementAccountBalance :one
UPDATE accounts
SET balance =  balance + $2, updated_at = now()
WHERE id = $1
RETURNING id, balance, currency, user_id, number, name, description, created_at
`

type IncrementAccountBalanceParams struct {
	ID      int64  `json:"id"`
	Balance string `json:"balance"`
}

type IncrementAccountBalanceRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (IncrementAccountBalanceRow, error) {
	row := q.queryRow(ctx, q.incrementAccountBalanceStmt, incrementAccountBalance, arg.ID, arg.Balance)
	var i IncrementAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByUserId = `-- name: ListAccountsByUserId :many
SELECT id, balance, currency, user_id, number, name, description, created_at
FROM accounts
WHERE user_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListAccountsByUserIdParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListAccountsByUserIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) ListAccountsByUserId(ctx context.Context, arg ListAccountsByUserIdParams) ([]ListAccountsByUserIdRow, error) {
	rows, err := q.query(ctx, q.listAccountsByUserIdStmt, listAccountsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByUserIdRow{}
	for rows.Next() {
		var i ListAccountsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Balance,
			&i.Currency,
			&i.UserID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
