// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const checkIsAccountWithIdExist = `-- name: CheckIsAccountWithIdExist :one
SELECT EXISTS (
    SELECT 1
    FROM accounts
    WHERE id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error) {
	row := q.queryRow(ctx, q.checkIsAccountWithIdExistStmt, checkIsAccountWithIdExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAccountsByUserId = `-- name: CountAccountsByUserId :one
SELECT COUNT(*) FROM accounts
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsByUserIdStmt, countAccountsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountsSearchByUserNumber = `-- name: CountAccountsSearchByUserNumber :one
SELECT COUNT(*)
FROM account_user_details_view
WHERE number LIKE '%' || $1 || '%'
  AND deleted_at IS NULL
`

func (q *Queries) CountAccountsSearchByUserNumber(ctx context.Context, number sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsSearchByUserNumberStmt, countAccountsSearchByUserNumber, number)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    number,
    name,
    description,
    balance,
    currency,
    user_id,
    is_main
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, balance, currency, user_id, number, name, description, is_main, created_at
`

type CreateAccountParams struct {
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	IsMain      bool           `json:"is_main"`
}

type CreateAccountRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.Balance,
		arg.Currency,
		arg.UserID,
		arg.IsMain,
	)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, balance, currency, user_id, number, name, description, is_main, created_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

type GetAccountByIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetAccountById(ctx context.Context, id int64) (GetAccountByIdRow, error) {
	row := q.queryRow(ctx, q.getAccountByIdStmt, getAccountById, id)
	var i GetAccountByIdRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByIdForUpdate = `-- name: GetAccountByIdForUpdate :one
SELECT id, balance, currency, user_id, number, name, description, is_main, created_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type GetAccountByIdForUpdateRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetAccountByIdForUpdate(ctx context.Context, id int64) (GetAccountByIdForUpdateRow, error) {
	row := q.queryRow(ctx, q.getAccountByIdForUpdateStmt, getAccountByIdForUpdate, id)
	var i GetAccountByIdForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const getMainAccountByUserId = `-- name: GetMainAccountByUserId :one
SELECT id, balance, currency, user_id, number, name, description, is_main, created_at
FROM accounts
WHERE user_id = $1 AND is_main = true AND deleted_at IS NULL
`

type GetMainAccountByUserIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) GetMainAccountByUserId(ctx context.Context, userID sql.NullInt64) (GetMainAccountByUserIdRow, error) {
	row := q.queryRow(ctx, q.getMainAccountByUserIdStmt, getMainAccountByUserId, userID)
	var i GetMainAccountByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const incrementAccountBalance = `-- name: IncrementAccountBalance :one
UPDATE accounts
SET balance =  balance + $2, updated_at = now()
WHERE id = $1
RETURNING id, balance, currency, user_id, number, name, description, is_main, created_at
`

type IncrementAccountBalanceParams struct {
	ID      int64  `json:"id"`
	Balance string `json:"balance"`
}

type IncrementAccountBalanceRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (IncrementAccountBalanceRow, error) {
	row := q.queryRow(ctx, q.incrementAccountBalanceStmt, incrementAccountBalance, arg.ID, arg.Balance)
	var i IncrementAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByUserId = `-- name: ListAccountsByUserId :many
SELECT
    id,
    balance,
    currency,
    created_at,
    updated_at,
    user_id,
    name,
    description,
    is_main,
    username,
    number
FROM account_user_details_view
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountsByUserIdParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListAccountsByUserIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserID      sql.NullInt64  `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	Username    sql.NullString `json:"username"`
	Number      sql.NullString `json:"number"`
}

func (q *Queries) ListAccountsByUserId(ctx context.Context, arg ListAccountsByUserIdParams) ([]ListAccountsByUserIdRow, error) {
	rows, err := q.query(ctx, q.listAccountsByUserIdStmt, listAccountsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByUserIdRow{}
	for rows.Next() {
		var i ListAccountsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsMain,
			&i.Username,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsSearchByUserNumber = `-- name: ListAccountsSearchByUserNumber :many
SELECT
    id,
    balance,
    currency,
    created_at,
    updated_at,
    user_id,
    name,
    description,
    is_main,
    username,
    number
FROM account_user_details_view
WHERE number LIKE '%' || $1 || '%'
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListAccountsSearchByUserNumberParams struct {
	Number      sql.NullString `json:"number"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type ListAccountsSearchByUserNumberRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserID      sql.NullInt64  `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	Username    sql.NullString `json:"username"`
	Number      sql.NullString `json:"number"`
}

func (q *Queries) ListAccountsSearchByUserNumber(ctx context.Context, arg ListAccountsSearchByUserNumberParams) ([]ListAccountsSearchByUserNumberRow, error) {
	rows, err := q.query(ctx, q.listAccountsSearchByUserNumberStmt, listAccountsSearchByUserNumber, arg.Number, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsSearchByUserNumberRow{}
	for rows.Next() {
		var i ListAccountsSearchByUserNumberRow
		if err := rows.Scan(
			&i.ID,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsMain,
			&i.Username,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransferDestinations = `-- name: ListRecentTransferDestinations :many
SELECT id, name, number, last_used_at FROM (
    SELECT DISTINCT ON (a.id) a.id, a.name, a.number, t.created_at AS last_used_at
    FROM transfers t
    JOIN accounts a ON a.id = t.to_account_id
    WHERE t.from_account_id = $1 AND a.deleted_at IS NULL
    ORDER BY a.id, t.created_at DESC
) recent_destinations
ORDER BY last_used_at DESC
LIMIT $2
`

type ListRecentTransferDestinationsParams struct {
	FromAccountID int64 `json:"from_account_id"`
	LimitCount    int32 `json:"limit_count"`
}

type ListRecentTransferDestinationsRow struct {
	ID         int64          `json:"id"`
	Name       sql.NullString `json:"name"`
	Number     sql.NullString `json:"number"`
	LastUsedAt time.Time      `json:"last_used_at"`
}

func (q *Queries) ListRecentTransferDestinations(ctx context.Context, arg ListRecentTransferDestinationsParams) ([]ListRecentTransferDestinationsRow, error) {
	rows, err := q.query(ctx, q.listRecentTransferDestinationsStmt, listRecentTransferDestinations, arg.FromAccountID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentTransferDestinationsRow{}
	for rows.Next() {
		var i ListRecentTransferDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Number,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :one
UPDATE accounts
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, balance, currency, user_id, number, name, description, is_main, created_at
`

type SoftDeleteAccountRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) SoftDeleteAccount(ctx context.Context, id int64) (SoftDeleteAccountRow, error) {
	row := q.queryRow(ctx, q.softDeleteAccountStmt, softDeleteAccount, id)
	var i SoftDeleteAccountRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, balance, currency, user_id, number, name, description, is_main, created_at
`

type UpdateAccountParams struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

type UpdateAccountRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.queryRow(ctx, q.updateAccountStmt, updateAccount, arg.ID, arg.Name, arg.Description)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}

const updateAccountNumber = `-- name: UpdateAccountNumber :one
UPDATE accounts
SET number = $2, updated_at = now()
WHERE id = $1
RETURNING id, balance, currency, user_id, number, name, description, is_main, created_at
`

type UpdateAccountNumberParams struct {
	ID     int64          `json:"id"`
	Number sql.NullString `json:"number"`
}

type UpdateAccountNumberRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	CreatedAt   time.Time      `json:"created_at"`
}

func (q *Queries) UpdateAccountNumber(ctx context.Context, arg UpdateAccountNumberParams) (UpdateAccountNumberRow, error) {
	row := q.queryRow(ctx, q.updateAccountNumberStmt, updateAccountNumber, arg.ID, arg.Number)
	var i UpdateAccountNumberRow
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.CreatedAt,
	)
	return i, err
}
