// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkIsAccountWithIdExistStmt, err = db.PrepareContext(ctx, checkIsAccountWithIdExist); err != nil {
		return nil, fmt.Errorf("error preparing query CheckIsAccountWithIdExist: %w", err)
	}
	if q.checkIsUsernameExistStmt, err = db.PrepareContext(ctx, checkIsUsernameExist); err != nil {
		return nil, fmt.Errorf("error preparing query CheckIsUsernameExist: %w", err)
	}
	if q.countAccountsByUserIdStmt, err = db.PrepareContext(ctx, countAccountsByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query CountAccountsByUserId: %w", err)
	}
	if q.countEntriesByAccountStmt, err = db.PrepareContext(ctx, countEntriesByAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CountEntriesByAccount: %w", err)
	}
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createEntriesStmt, err = db.PrepareContext(ctx, createEntries); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEntries: %w", err)
	}
	if q.createTransferStmt, err = db.PrepareContext(ctx, createTransfer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransfer: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getAccountByIdStmt, err = db.PrepareContext(ctx, getAccountById); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountById: %w", err)
	}
	if q.getAccountByIdForUpdateStmt, err = db.PrepareContext(ctx, getAccountByIdForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByIdForUpdate: %w", err)
	}
	if q.getTransferByIdStmt, err = db.PrepareContext(ctx, getTransferById); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransferById: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserById: %w", err)
	}
	if q.incrementAccountBalanceStmt, err = db.PrepareContext(ctx, incrementAccountBalance); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementAccountBalance: %w", err)
	}
	if q.listAccountsByUserIdStmt, err = db.PrepareContext(ctx, listAccountsByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccountsByUserId: %w", err)
	}
	if q.listEntriesByAccountStmt, err = db.PrepareContext(ctx, listEntriesByAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ListEntriesByAccount: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkIsAccountWithIdExistStmt != nil {
		if cerr := q.checkIsAccountWithIdExistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkIsAccountWithIdExistStmt: %w", cerr)
		}
	}
	if q.checkIsUsernameExistStmt != nil {
		if cerr := q.checkIsUsernameExistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkIsUsernameExistStmt: %w", cerr)
		}
	}
	if q.countAccountsByUserIdStmt != nil {
		if cerr := q.countAccountsByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAccountsByUserIdStmt: %w", cerr)
		}
	}
	if q.countEntriesByAccountStmt != nil {
		if cerr := q.countEntriesByAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countEntriesByAccountStmt: %w", cerr)
		}
	}
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createEntriesStmt != nil {
		if cerr := q.createEntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEntriesStmt: %w", cerr)
		}
	}
	if q.createTransferStmt != nil {
		if cerr := q.createTransferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransferStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getAccountByIdStmt != nil {
		if cerr := q.getAccountByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByIdStmt: %w", cerr)
		}
	}
	if q.getAccountByIdForUpdateStmt != nil {
		if cerr := q.getAccountByIdForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByIdForUpdateStmt: %w", cerr)
		}
	}
	if q.getTransferByIdStmt != nil {
		if cerr := q.getTransferByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransferByIdStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.incrementAccountBalanceStmt != nil {
		if cerr := q.incrementAccountBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementAccountBalanceStmt: %w", cerr)
		}
	}
	if q.listAccountsByUserIdStmt != nil {
		if cerr := q.listAccountsByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccountsByUserIdStmt: %w", cerr)
		}
	}
	if q.listEntriesByAccountStmt != nil {
		if cerr := q.listEntriesByAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listEntriesByAccountStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	checkIsAccountWithIdExistStmt *sql.Stmt
	checkIsUsernameExistStmt      *sql.Stmt
	countAccountsByUserIdStmt     *sql.Stmt
	countEntriesByAccountStmt     *sql.Stmt
	createAccountStmt             *sql.Stmt
	createEntriesStmt             *sql.Stmt
	createTransferStmt            *sql.Stmt
	createUserStmt                *sql.Stmt
	getAccountByIdStmt            *sql.Stmt
	getAccountByIdForUpdateStmt   *sql.Stmt
	getTransferByIdStmt           *sql.Stmt
	getUserByEmailStmt            *sql.Stmt
	getUserByIdStmt               *sql.Stmt
	incrementAccountBalanceStmt   *sql.Stmt
	listAccountsByUserIdStmt      *sql.Stmt
	listEntriesByAccountStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		checkIsAccountWithIdExistStmt: q.checkIsAccountWithIdExistStmt,
		checkIsUsernameExistStmt:      q.checkIsUsernameExistStmt,
		countAccountsByUserIdStmt:     q.countAccountsByUserIdStmt,
		countEntriesByAccountStmt:     q.countEntriesByAccountStmt,
		createAccountStmt:             q.createAccountStmt,
		createEntriesStmt:             q.createEntriesStmt,
		createTransferStmt:            q.createTransferStmt,
		createUserStmt:                q.createUserStmt,
		getAccountByIdStmt:            q.getAccountByIdStmt,
		getAccountByIdForUpdateStmt:   q.getAccountByIdForUpdateStmt,
		getTransferByIdStmt:           q.getTransferByIdStmt,
		getUserByEmailStmt:            q.getUserByEmailStmt,
		getUserByIdStmt:               q.getUserByIdStmt,
		incrementAccountBalanceStmt:   q.incrementAccountBalanceStmt,
		listAccountsByUserIdStmt:      q.listAccountsByUserIdStmt,
		listEntriesByAccountStmt:      q.listEntriesByAccountStmt,
	}
}
