// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
)

const createEntries = `-- name: CreateEntries :one
INSERT INTO entries (
    account_id,
    type,
    amount
) VALUES (
    $1, $2, $3
)
RETURNING id, account_id, type, amount, created_at
`

type CreateEntriesParams struct {
	AccountID int64  `json:"account_id"`
	Type      string `json:"type"`
	Amount    string `json:"amount"`
}

func (q *Queries) CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error) {
	row := q.queryRow(ctx, q.createEntriesStmt, createEntries, arg.AccountID, arg.Type, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
