// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

// Table to store account information
type Account struct {
	ID    int64  `json:"id"`
	Owner string `json:"owner"`
	// Balance cannot be negative, it is the amount of money in the account
	Balance   string        `json:"balance"`
	Currency  string        `json:"currency"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	UserID    sql.NullInt64 `json:"user_id"`
}

// Table to store account entries for each transaction
type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// Type use to define the purpose of the entry
	Type string `json:"type"`
	// Amount cannot be negative, it is the amount of money added or subtracted from the account
	Amount    string        `json:"amount"`
	CreatedAt time.Time     `json:"created_at"`
	UserID    sql.NullInt64 `json:"user_id"`
}

// Table to store transfer transactions between accounts
type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// Amount cannot be negative, it is the amount of money transferred from one account to another
	Amount    string    `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

// Table to store user accounts used for authentication
type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	// Password hash generated with bcrypt, plaintext passwords are never stored
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
