// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error)
	CheckIsUsernameExist(ctx context.Context, username string) (bool, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAccountById(ctx context.Context, id int64) (GetAccountByIdRow, error)
	GetAccountByIdForUpdate(ctx context.Context, id int64) (GetAccountByIdForUpdateRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (IncrementAccountBalanceRow, error)
}

var _ Querier = (*Queries)(nil)
