services:
  postgres:
    image: postgres:16-alpine
    container_name: core-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: simple_bank
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_bank
    ports:
      - "5433:5432"
    volumes:
      - core-service-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simple_bank -d simple_bank"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./internal/db/migrations:/migrations
    entrypoint:
      - migrate
      - -path
      - /migrations
      - -database
      - postgres://simple_bank:password@postgres:5432/simple_bank?sslmode=disable
      - up

volumes:
  core-service-db-data:
