terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# --- Networking: use the account's default VPC/subnet ---

data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}

# --- AMI: latest Amazon Linux 2023 ---

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- SSH key pair: generated by Terraform, private key saved locally ---

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "core-service-key"
  public_key = tls_private_key.this.public_key_openssh
}

resource "local_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/core-service-key.pem"
  file_permission = "0600"
}

# --- Security group: SSH + nginx (the only public entrypoint) ---
#
# app_port is deliberately not opened here — core-service is only reachable
# from nginx over the internal docker network (see user_data.sh.tpl), and
# from the instance itself via the 127.0.0.1-bound debug port.

resource "aws_security_group" "core_service" {
  name        = "core-service-sg"
  description = "Allow SSH and nginx traffic to the core-service host"
  vpc_id      = data.aws_vpc.default.id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = var.ssh_cidr_blocks
  }

  ingress {
    description = "nginx (reverse proxy + rate limiter in front of core-service)"
    from_port   = var.nginx_port
    to_port     = var.nginx_port
    protocol    = "tcp"
    cidr_blocks = var.app_cidr_blocks
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# --- nginx config: rendered here so main.tf/variables.tf stay the single
#     source of truth for ports and rate-limit knobs, then shipped to the
#     instance base64-encoded inside user_data (see Section on user_data.sh.tpl) ---

locals {
  nginx_conf = templatefile("${path.module}/nginx.conf.tpl", {
    nginx_port       = var.nginx_port
    app_port         = var.app_port
    rate_limit_rps   = var.nginx_rate_limit_rps
    rate_limit_burst = var.nginx_rate_limit_burst
  })

  # core-service + nginx as a compose stack, so the instance (and CI's SSH
  # redeploy step) manage both containers with `docker compose` instead of
  # hand-rolled `docker run`/`docker network create` calls. Fully resolved at
  # render time (like nginx_conf above) — no env-var substitution happens on
  # the instance itself.
  docker_compose_yml = templatefile("${path.module}/docker-compose.prod.yaml", {
    docker_image = var.docker_image
    app_port     = var.app_port
    nginx_image  = var.nginx_image
    nginx_port   = var.nginx_port
  })

  # Pulled into its own local (rather than inlined in aws_instance below) so
  # it can also be exposed via outputs.tf's rendered_user_data — EC2 only
  # runs this script on an instance's first boot, so re-running it by hand
  # over SSH is how an already-running instance picks up config changes
  # (see docs/TERRAFORM_EC2_DEPLOY.md Section 7). Reusing this exact value
  # for both means there's no separate, driftable "redeploy script."
  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    app_port                  = var.app_port
    docker_compose_version    = var.docker_compose_version
    db_driver                 = var.db_driver
    db_source                 = var.db_source
    jwt_secret_key            = var.jwt_secret_key
    jwt_access_token_duration = var.jwt_access_token_duration
    cors_allowed_origins      = var.cors_allowed_origins
    rate_limit_enabled        = var.app_rate_limit_enabled
    rate_limit_rps            = var.app_rate_limit_rps
    rate_limit_burst          = var.app_rate_limit_burst
    nginx_conf_base64         = base64encode(local.nginx_conf)
    docker_compose_yml_base64 = base64encode(local.docker_compose_yml)
  })
}

# --- EC2 instance running core-service behind an nginx reverse proxy ---

resource "aws_instance" "core_service" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  subnet_id              = data.aws_subnets.default.ids[0]
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.core_service.id]

  user_data = local.user_data

  tags = {
    Name = "core-service"
  }
}