// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account-manage.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countAccountsByUserId = `-- name: CountAccountsByUserId :one
SELECT COUNT(*) FROM accounts
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsByUserIdStmt, countAccountsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAccountsByUserId = `-- name: ListAccountsByUserId :many
SELECT
    id,
    balance,
    currency,
    created_at,
    updated_at,
    user_id,
    name,
    description,
    is_main,
    username,
    number
FROM account_user_details_view
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountsByUserIdParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

type ListAccountsByUserIdRow struct {
	ID          int64          `json:"id"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	UserID      sql.NullInt64  `json:"user_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	IsMain      bool           `json:"is_main"`
	Username    sql.NullString `json:"username"`
	Number      sql.NullString `json:"number"`
}

func (q *Queries) ListAccountsByUserId(ctx context.Context, arg ListAccountsByUserIdParams) ([]ListAccountsByUserIdRow, error) {
	rows, err := q.query(ctx, q.listAccountsByUserIdStmt, listAccountsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsByUserIdRow{}
	for rows.Next() {
		var i ListAccountsByUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsMain,
			&i.Username,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
