// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const countAccountsSearchByUserNumber = `-- name: CountAccountsSearchByUserNumber :one
SELECT COUNT(*)
FROM account_user_details_view
WHERE number LIKE '%' || $1 || '%'
`

func (q *Queries) CountAccountsSearchByUserNumber(ctx context.Context, number sql.NullString) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsSearchByUserNumberStmt, countAccountsSearchByUserNumber, number)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    number,
    name,
    description,
    balance,
    currency,
    user_id,
    is_main
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
`

type CreateAccountParams struct {
	Number      sql.NullString `json:"number"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Balance     string         `json:"balance"`
	Currency    string         `json:"currency"`
	UserID      sql.NullInt64  `json:"user_id"`
	IsMain      bool           `json:"is_main"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.Balance,
		arg.Currency,
		arg.UserID,
		arg.IsMain,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountById(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIdStmt, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const getMainAccountByUserId = `-- name: GetMainAccountByUserId :one
SELECT id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
FROM accounts
WHERE user_id = $1 AND is_main = true AND deleted_at IS NULL
`

func (q *Queries) GetMainAccountByUserId(ctx context.Context, userID sql.NullInt64) (Account, error) {
	row := q.queryRow(ctx, q.getMainAccountByUserIdStmt, getMainAccountByUserId, userID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsSearchByUserNumber = `-- name: ListAccountsSearchByUserNumber :many
SELECT v.id, v.balance, v.currency, v.created_at, v.updated_at, v.user_id, v.name, v.description, v.is_main, v.number, v.username
FROM account_user_details_view v
WHERE v.number LIKE '%' || $1 || '%'
ORDER BY v.created_at DESC
LIMIT $3
OFFSET $2
`

type ListAccountsSearchByUserNumberParams struct {
	Number      sql.NullString `json:"number"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type ListAccountsSearchByUserNumberRow struct {
	AccountUserDetailsView AccountUserDetailsView `json:"account_user_details_view"`
}

func (q *Queries) ListAccountsSearchByUserNumber(ctx context.Context, arg ListAccountsSearchByUserNumberParams) ([]ListAccountsSearchByUserNumberRow, error) {
	rows, err := q.query(ctx, q.listAccountsSearchByUserNumberStmt, listAccountsSearchByUserNumber, arg.Number, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountsSearchByUserNumberRow{}
	for rows.Next() {
		var i ListAccountsSearchByUserNumberRow
		if err := rows.Scan(
			&i.AccountUserDetailsView.ID,
			&i.AccountUserDetailsView.Balance,
			&i.AccountUserDetailsView.Currency,
			&i.AccountUserDetailsView.CreatedAt,
			&i.AccountUserDetailsView.UpdatedAt,
			&i.AccountUserDetailsView.UserID,
			&i.AccountUserDetailsView.Name,
			&i.AccountUserDetailsView.Description,
			&i.AccountUserDetailsView.IsMain,
			&i.AccountUserDetailsView.Number,
			&i.AccountUserDetailsView.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :one
UPDATE accounts
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.softDeleteAccountStmt, softDeleteAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
`

type UpdateAccountParams struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.updateAccountStmt, updateAccount, arg.ID, arg.Name, arg.Description)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountNumber = `-- name: UpdateAccountNumber :one
UPDATE accounts
SET number = $2, updated_at = now()
WHERE id = $1
RETURNING id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
`

type UpdateAccountNumberParams struct {
	ID     int64          `json:"id"`
	Number sql.NullString `json:"number"`
}

func (q *Queries) UpdateAccountNumber(ctx context.Context, arg UpdateAccountNumberParams) (Account, error) {
	row := q.queryRow(ctx, q.updateAccountNumberStmt, updateAccountNumber, arg.ID, arg.Number)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}
