// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account-manage.sql

package db

import (
	"context"
	"database/sql"
)

const countAccountsByUserId = `-- name: CountAccountsByUserId :one
SELECT COUNT(*) FROM accounts
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.queryRow(ctx, q.countAccountsByUserIdStmt, countAccountsByUserId, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMeAccountsByUserId = `-- name: ListMeAccountsByUserId :many
SELECT v.id, v.balance, v.currency, v.created_at, v.updated_at, v.user_id, v.name, v.description, v.is_main, v.number, v.username
FROM account_user_details_view v
WHERE v.user_id = $1
    AND v.name LIKE '%' || $2 || '%'
ORDER BY v.created_at DESC
LIMIT  $4 OFFSET  $3
`

type ListMeAccountsByUserIdParams struct {
	UserID      sql.NullInt64  `json:"user_id"`
	Name        sql.NullString `json:"name"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type ListMeAccountsByUserIdRow struct {
	AccountUserDetailsView AccountUserDetailsView `json:"account_user_details_view"`
}

func (q *Queries) ListMeAccountsByUserId(ctx context.Context, arg ListMeAccountsByUserIdParams) ([]ListMeAccountsByUserIdRow, error) {
	rows, err := q.query(ctx, q.listMeAccountsByUserIdStmt, listMeAccountsByUserId,
		arg.UserID,
		arg.Name,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeAccountsByUserIdRow{}
	for rows.Next() {
		var i ListMeAccountsByUserIdRow
		if err := rows.Scan(
			&i.AccountUserDetailsView.ID,
			&i.AccountUserDetailsView.Balance,
			&i.AccountUserDetailsView.Currency,
			&i.AccountUserDetailsView.CreatedAt,
			&i.AccountUserDetailsView.UpdatedAt,
			&i.AccountUserDetailsView.UserID,
			&i.AccountUserDetailsView.Name,
			&i.AccountUserDetailsView.Description,
			&i.AccountUserDetailsView.IsMain,
			&i.AccountUserDetailsView.Number,
			&i.AccountUserDetailsView.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeAccountsByUserIdCount = `-- name: ListMeAccountsByUserIdCount :one
SELECT
    COUNT(*)
FROM account_user_details_view
WHERE user_id = $1
    AND name LIKE '%' || $2 || '%'
`

type ListMeAccountsByUserIdCountParams struct {
	UserID sql.NullInt64  `json:"user_id"`
	Name   sql.NullString `json:"name"`
}

func (q *Queries) ListMeAccountsByUserIdCount(ctx context.Context, arg ListMeAccountsByUserIdCountParams) (int64, error) {
	row := q.queryRow(ctx, q.listMeAccountsByUserIdCountStmt, listMeAccountsByUserIdCount, arg.UserID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
