// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account-transaction.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const accountEntriesByAccountId = `-- name: AccountEntriesByAccountId :one
SELECT v.account_name, v.account_number, v.is_main, v.to_account_name, v.to_account_number, v.id, v.user_id, v.account_id, v.created_at, v.to_account_id, v.type, v.amount, v.description
FROM account_entries_view v
WHERE v.id = $1
`

type AccountEntriesByAccountIdRow struct {
	AccountEntriesView AccountEntriesView `json:"account_entries_view"`
}

func (q *Queries) AccountEntriesByAccountId(ctx context.Context, id int64) (AccountEntriesByAccountIdRow, error) {
	row := q.queryRow(ctx, q.accountEntriesByAccountIdStmt, accountEntriesByAccountId, id)
	var i AccountEntriesByAccountIdRow
	err := row.Scan(
		&i.AccountEntriesView.AccountName,
		&i.AccountEntriesView.AccountNumber,
		&i.AccountEntriesView.IsMain,
		&i.AccountEntriesView.ToAccountName,
		&i.AccountEntriesView.ToAccountNumber,
		&i.AccountEntriesView.ID,
		&i.AccountEntriesView.UserID,
		&i.AccountEntriesView.AccountID,
		&i.AccountEntriesView.CreatedAt,
		&i.AccountEntriesView.ToAccountID,
		&i.AccountEntriesView.Type,
		&i.AccountEntriesView.Amount,
		&i.AccountEntriesView.Description,
	)
	return i, err
}

const checkIsAccountWithIdExist = `-- name: CheckIsAccountWithIdExist :one
SELECT EXISTS (
    SELECT 1
    FROM accounts
    WHERE id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error) {
	row := q.queryRow(ctx, q.checkIsAccountWithIdExistStmt, checkIsAccountWithIdExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAccountEntriesByAccountId = `-- name: CountAccountEntriesByAccountId :one
SELECT COUNT(*)
FROM account_entries_view
WHERE account_id = $1
  AND (
      $2::timestamptz IS NULL
      OR created_at >= $2::timestamptz
  )
  AND (
      $3::timestamptz IS NULL
      OR created_at < $3::timestamptz
  )
  AND (
      $4::varchar IS NULL
      OR type = $4::varchar
  )
`

type CountAccountEntriesByAccountIdParams struct {
	AccountID   int64          `json:"account_id"`
	PeriodStart sql.NullTime   `json:"period_start"`
	PeriodEnd   sql.NullTime   `json:"period_end"`
	EntryType   sql.NullString `json:"entry_type"`
}

func (q *Queries) CountAccountEntriesByAccountId(ctx context.Context, arg CountAccountEntriesByAccountIdParams) (int64, error) {
	row := q.queryRow(ctx, q.countAccountEntriesByAccountIdStmt, countAccountEntriesByAccountId,
		arg.AccountID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntryType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAccountByIdForUpdate = `-- name: GetAccountByIdForUpdate :one
SELECT id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetAccountByIdForUpdate(ctx context.Context, id int64) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIdForUpdateStmt, getAccountByIdForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountViewById = `-- name: GetAccountViewById :one
SELECT v.id, v.balance, v.currency, v.created_at, v.updated_at, v.user_id, v.name, v.description, v.is_main, v.number, v.username
FROM account_user_details_view v
WHERE v.id = $1
`

type GetAccountViewByIdRow struct {
	AccountUserDetailsView AccountUserDetailsView `json:"account_user_details_view"`
}

func (q *Queries) GetAccountViewById(ctx context.Context, id int64) (GetAccountViewByIdRow, error) {
	row := q.queryRow(ctx, q.getAccountViewByIdStmt, getAccountViewById, id)
	var i GetAccountViewByIdRow
	err := row.Scan(
		&i.AccountUserDetailsView.ID,
		&i.AccountUserDetailsView.Balance,
		&i.AccountUserDetailsView.Currency,
		&i.AccountUserDetailsView.CreatedAt,
		&i.AccountUserDetailsView.UpdatedAt,
		&i.AccountUserDetailsView.UserID,
		&i.AccountUserDetailsView.Name,
		&i.AccountUserDetailsView.Description,
		&i.AccountUserDetailsView.IsMain,
		&i.AccountUserDetailsView.Number,
		&i.AccountUserDetailsView.Username,
	)
	return i, err
}

const incrementAccountBalance = `-- name: IncrementAccountBalance :one
UPDATE accounts
SET balance =  balance + $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, balance, currency, created_at, updated_at, user_id, number, name, description, is_main, deleted_at
`

type IncrementAccountBalanceParams struct {
	ID      int64  `json:"id"`
	Balance string `json:"balance"`
}

func (q *Queries) IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (Account, error) {
	row := q.queryRow(ctx, q.incrementAccountBalanceStmt, incrementAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.IsMain,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountEntriesByAccountId = `-- name: ListAccountEntriesByAccountId :many
SELECT v.account_name, v.account_number, v.is_main, v.to_account_name, v.to_account_number, v.id, v.user_id, v.account_id, v.created_at, v.to_account_id, v.type, v.amount, v.description
FROM account_entries_view v
WHERE v.account_id = $1
  AND (
      $2::timestamptz IS NULL
      OR v.created_at >= $2::timestamptz
  )
  AND (
      $3::timestamptz IS NULL
      OR v.created_at < $3::timestamptz
  )
  AND (
      $4::varchar IS NULL
      OR v.type = $4::varchar
  )
ORDER BY v.created_at DESC, v.id DESC
LIMIT $6
OFFSET $5
`

type ListAccountEntriesByAccountIdParams struct {
	AccountID   int64          `json:"account_id"`
	PeriodStart sql.NullTime   `json:"period_start"`
	PeriodEnd   sql.NullTime   `json:"period_end"`
	EntryType   sql.NullString `json:"entry_type"`
	OffsetCount int32          `json:"offset_count"`
	LimitCount  int32          `json:"limit_count"`
}

type ListAccountEntriesByAccountIdRow struct {
	AccountEntriesView AccountEntriesView `json:"account_entries_view"`
}

func (q *Queries) ListAccountEntriesByAccountId(ctx context.Context, arg ListAccountEntriesByAccountIdParams) ([]ListAccountEntriesByAccountIdRow, error) {
	rows, err := q.query(ctx, q.listAccountEntriesByAccountIdStmt, listAccountEntriesByAccountId,
		arg.AccountID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntryType,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountEntriesByAccountIdRow{}
	for rows.Next() {
		var i ListAccountEntriesByAccountIdRow
		if err := rows.Scan(
			&i.AccountEntriesView.AccountName,
			&i.AccountEntriesView.AccountNumber,
			&i.AccountEntriesView.IsMain,
			&i.AccountEntriesView.ToAccountName,
			&i.AccountEntriesView.ToAccountNumber,
			&i.AccountEntriesView.ID,
			&i.AccountEntriesView.UserID,
			&i.AccountEntriesView.AccountID,
			&i.AccountEntriesView.CreatedAt,
			&i.AccountEntriesView.ToAccountID,
			&i.AccountEntriesView.Type,
			&i.AccountEntriesView.Amount,
			&i.AccountEntriesView.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransferDestinations = `-- name: ListRecentTransferDestinations :many
SELECT 
    id, 
    name, 
    number, 
    username, 
    user_id,
    last_used_at 
FROM (
    SELECT 
    	DISTINCT ON (a.id) a.id,
         a.name, 
         a.number, 
         t.created_at AS last_used_at, 
         u.username as username,
         u.id as user_id
    FROM transfers t
    JOIN accounts a ON a.id = t.to_account_id
    join users u on u.id = a.user_id
    WHERE t.from_account_id = $1 AND a.deleted_at IS NULL
    ORDER BY a.id, t.created_at DESC
) recent_destinations
ORDER BY last_used_at desc
LIMIT $3
OFFSET $2
`

type ListRecentTransferDestinationsParams struct {
	FromAccountID int64 `json:"from_account_id"`
	OffsetCount   int32 `json:"offset_count"`
	LimitCount    int32 `json:"limit_count"`
}

type ListRecentTransferDestinationsRow struct {
	ID         int64          `json:"id"`
	Name       sql.NullString `json:"name"`
	Number     sql.NullString `json:"number"`
	Username   string         `json:"username"`
	UserID     int64          `json:"user_id"`
	LastUsedAt time.Time      `json:"last_used_at"`
}

func (q *Queries) ListRecentTransferDestinations(ctx context.Context, arg ListRecentTransferDestinationsParams) ([]ListRecentTransferDestinationsRow, error) {
	rows, err := q.query(ctx, q.listRecentTransferDestinationsStmt, listRecentTransferDestinations, arg.FromAccountID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentTransferDestinationsRow{}
	for rows.Next() {
		var i ListRecentTransferDestinationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Number,
			&i.Username,
			&i.UserID,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
