// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AccountEntriesByAccountId(ctx context.Context, id int64) (AccountEntriesByAccountIdRow, error)
	CheckIsAccountWithIdExist(ctx context.Context, id int64) (bool, error)
	CheckIsUsernameExist(ctx context.Context, username string) (bool, error)
	CountAccountEntriesByAccountId(ctx context.Context, arg CountAccountEntriesByAccountIdParams) (int64, error)
	CountAccountTransactionHistory(ctx context.Context, arg CountAccountTransactionHistoryParams) (int64, error)
	CountAccountsByUserId(ctx context.Context, userID sql.NullInt64) (int64, error)
	CountAccountsSearchByUserNumber(ctx context.Context, number sql.NullString) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetAccountByIdForUpdate(ctx context.Context, id int64) (Account, error)
	GetAccountViewById(ctx context.Context, id int64) (GetAccountViewByIdRow, error)
	GetMainAccountByUserId(ctx context.Context, userID sql.NullInt64) (Account, error)
	GetTransferById(ctx context.Context, id int64) (Transfer, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error)
	IncrementAccountBalance(ctx context.Context, arg IncrementAccountBalanceParams) (Account, error)
	ListAccountEntriesByAccountId(ctx context.Context, arg ListAccountEntriesByAccountIdParams) ([]ListAccountEntriesByAccountIdRow, error)
	ListAccountTransactionHistory(ctx context.Context, arg ListAccountTransactionHistoryParams) ([]ListAccountTransactionHistoryRow, error)
	ListAccountsSearchByUserNumber(ctx context.Context, arg ListAccountsSearchByUserNumberParams) ([]ListAccountsSearchByUserNumberRow, error)
	ListMeAccountsByUserId(ctx context.Context, arg ListMeAccountsByUserIdParams) ([]ListMeAccountsByUserIdRow, error)
	ListMeAccountsByUserIdCount(ctx context.Context, arg ListMeAccountsByUserIdCountParams) (int64, error)
	ListRecentTransferDestinations(ctx context.Context, arg ListRecentTransferDestinationsParams) ([]ListRecentTransferDestinationsRow, error)
	SoftDeleteAccount(ctx context.Context, id int64) (Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountNumber(ctx context.Context, arg UpdateAccountNumberParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
