// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"time"
)

const bindUserDeviceFingerprint = `-- name: BindUserDeviceFingerprint :one
UPDATE users
SET device_fingerprint_hash = $2, updated_at = now()
WHERE id = $1 AND device_fingerprint_hash = ''
RETURNING id, username, email, created_at
`

type BindUserDeviceFingerprintParams struct {
	ID                    int64  `json:"id"`
	DeviceFingerprintHash string `json:"device_fingerprint_hash"`
}

type BindUserDeviceFingerprintRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

// Binds an unbound (pre-migration, device_fingerprint_hash = ”) user row to
// the fingerprint presented on its first login after the migration. Never
// overwrites an already-bound row.
func (q *Queries) BindUserDeviceFingerprint(ctx context.Context, arg BindUserDeviceFingerprintParams) (BindUserDeviceFingerprintRow, error) {
	row := q.queryRow(ctx, q.bindUserDeviceFingerprintStmt, bindUserDeviceFingerprint, arg.ID, arg.DeviceFingerprintHash)
	var i BindUserDeviceFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const checkIsUsernameExist = `-- name: CheckIsUsernameExist :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE username = $1
)
`

func (q *Queries) CheckIsUsernameExist(ctx context.Context, username string) (bool, error) {
	row := q.queryRow(ctx, q.checkIsUsernameExistStmt, checkIsUsernameExist, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    device_fingerprint_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, username, email, created_at
`

type CreateUserParams struct {
	Username              string `json:"username"`
	Email                 string `json:"email"`
	DeviceFingerprintHash string `json:"device_fingerprint_hash"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Email, arg.DeviceFingerprintHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, device_fingerprint_hash, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                    int64     `json:"id"`
	Username              string    `json:"username"`
	Email                 string    `json:"email"`
	DeviceFingerprintHash string    `json:"device_fingerprint_hash"`
	CreatedAt             time.Time `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DeviceFingerprintHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, created_at
FROM users
WHERE id = $1
`

type GetUserByIdRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.queryRow(ctx, q.getUserByIdStmt, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
